### ISSUE TITLE
Update license to MIT? (or other)

### ISSUE THREAD

**Issue by alx-a** [sanel/magic-ed#4]
Use however You like matches the MIT license pretty well.

If we also want to submit to quicklisp, the license should be updated to some standard.
If change is approved and I'm added as a dev,  I can update the readme file and project to the MIT license. 

Alternatively, pick a license of Your choice from the list and add it to the project according to instructions here:
https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository#including-an-open-source-license-in-your-repository

UPDATE: addedd  a proposed MIT license in a separate pull request

**Comment by sanel** [comment]
MIT is fine with me. Thanks!
